// Example supplier data
export const suppliers = [
  { id: 1, name: "AI Innovators", description: "Provides advanced AI-driven analytics for manufacturing.", gartnerScore: 4.5, website: "https://ai-innovators.com", logo: "https://logo.clearbit.com/ai-innovators.com", ndaStatus: "approved" },
  { id: 2, name: "Cognitive Solutions", description: "Specializes in natural language processing and chatbots.", gartnerScore: 4.2, website: "https://cognitivesolutions.com", logo: "https://logo.clearbit.com/cognitivesolutions.com", ndaStatus: "missing" },
  { id: 3, name: "Visionary AI", description: "Offers computer vision solutions for quality control.", gartnerScore: 4.7, website: "https://visionaryai.com", logo: "https://logo.clearbit.com/visionaryai.com", ndaStatus: "approved" },
  { id: 4, name: "SmartData Corp", description: "AI-powered data integration and management.", gartnerScore: 4.3, website: "https://smartdatacorp.com", logo: "https://logo.clearbit.com/smartdatacorp.com", ndaStatus: "missing" },
  { id: 5, name: "DeepLearn Systems", description: "Deep learning solutions for predictive maintenance.", gartnerScore: 4.6, website: "https://deeplearnsystems.com", logo: "https://logo.clearbit.com/deeplearnsystems.com" },
  { id: 6, name: "Insight Robotics", description: "Robotic process automation with AI insights.", gartnerScore: 4.1, website: "https://insightrobotics.com", logo: "https://logo.clearbit.com/insightrobotics.com" },
  { id: 7, name: "NextGen AI", description: "Next generation AI for supply chain optimization.", gartnerScore: 4.4, website: "https://nextgenai.com", logo: "https://logo.clearbit.com/nextgenai.com" },
  { id: 8, name: "BlueMind Analytics", description: "AI-driven business intelligence and dashboards.", gartnerScore: 4.0, website: "https://bluemindanalytics.com", logo: "https://logo.clearbit.com/bluemindanalytics.com" },
  { id: 9, name: "Quantum Vision", description: "Quantum computing meets AI for advanced simulations.", gartnerScore: 4.8, website: "https://quantumvision.com", logo: "https://logo.clearbit.com/quantumvision.com" },
  { id: 10, name: "Predictify", description: "Predictive analytics for sales and marketing.", gartnerScore: 4.3, website: "https://predictify.com", logo: "https://logo.clearbit.com/predictify.com" },
  { id: 11, name: "AI SecureTech", description: "AI-based cybersecurity solutions.", gartnerScore: 4.5, website: "https://aisecuretech.com", logo: "https://logo.clearbit.com/aisecuretech.com" },
  { id: 12, name: "GreenAI", description: "Sustainable AI for energy management.", gartnerScore: 4.2, website: "https://greenai.com", logo: "https://logo.clearbit.com/greenai.com" },
  { id: 13, name: "MedAI Solutions", description: "AI for medical diagnostics and patient care.", gartnerScore: 4.7, website: "https://medaisolutions.com", logo: "https://logo.clearbit.com/medaisolutions.com" },
  { id: 14, name: "RetailGenius", description: "Retail analytics and customer insights with AI.", gartnerScore: 4.4, website: "https://retailgenius.com", logo: "https://logo.clearbit.com/retailgenius.com" },
  { id: 15, name: "AutoPilot AI", description: "Autonomous vehicle and fleet management AI.", gartnerScore: 4.6, website: "https://autopilotai.com", logo: "https://logo.clearbit.com/autopilotai.com" },
  { id: 16, name: "EdgeAI Tech", description: "Edge computing with embedded AI models.", gartnerScore: 4.1, website: "https://edgeaitech.com", logo: "https://logo.clearbit.com/edgeaitech.com" },
  { id: 17, name: "AI TranslatePro", description: "AI-powered translation and localization.", gartnerScore: 4.3, website: "https://aitranslatepro.com", logo: "https://logo.clearbit.com/aitranslatepro.com" },
  { id: 18, name: "LogiAI", description: "Logistics and route optimization using AI.", gartnerScore: 4.2, website: "https://logiai.com", logo: "https://logo.clearbit.com/logiai.com" },
  { id: 19, name: "AI Tutor", description: "Personalized AI tutoring for students.", gartnerScore: 4.5, website: "https://aitutor.com", logo: "https://logo.clearbit.com/aitutor.com" },
  { id: 20, name: "SmartVision Medical", description: "AI for medical imaging and diagnostics.", gartnerScore: 4.8, website: "https://smartvisionmedical.com", logo: "https://logo.clearbit.com/smartvisionmedical.com" },
  { id: 21, name: "AI Recruiter", description: "AI-driven recruitment and talent management.", gartnerScore: 4.0, website: "https://airecruiter.com", logo: "https://logo.clearbit.com/airecruiter.com" },
  { id: 22, name: "UrbanAI", description: "AI for smart city infrastructure and planning.", gartnerScore: 4.4, website: "https://urbanai.com", logo: "https://logo.clearbit.com/urbanai.com" },
  { id: 23, name: "AI Chem", description: "AI for chemical process optimization.", gartnerScore: 4.3, website: "https://aichem.com", logo: "https://logo.clearbit.com/aichem.com" },
  { id: 24, name: "AI Detect", description: "Fraud detection and risk management with AI.", gartnerScore: 4.6, website: "https://aidetect.com", logo: "https://logo.clearbit.com/aidetect.com" },
  { id: 25, name: "AI Compose", description: "AI-generated content and copywriting.", gartnerScore: 4.1, website: "https://aicompose.com", logo: "https://logo.clearbit.com/aicompose.com" },
  { id: 26, name: "AI FarmTech", description: "AI for precision agriculture and crop monitoring.", gartnerScore: 4.7, website: "https://aifarmtech.com", logo: "https://logo.clearbit.com/aifarmtech.com" },
  { id: 27, name: "AI FleetOps", description: "Fleet operations and telematics with AI.", gartnerScore: 4.2, website: "https://aifleetops.com", logo: "https://logo.clearbit.com/aifleetops.com" },
  { id: 28, name: "AI HealthNet", description: "AI for healthcare network optimization.", gartnerScore: 4.5, website: "https://aihealthnet.com", logo: "https://logo.clearbit.com/aihealthnet.com" },
  { id: 29, name: "AI BuildPro", description: "AI for construction project management.", gartnerScore: 4.3, website: "https://aibuildpro.com", logo: "https://logo.clearbit.com/aibuildpro.com" },
  { id: 30, name: "AI MarketSense", description: "Market research and sentiment analysis with AI.", gartnerScore: 4.4, website: "https://aimarketsense.com", logo: "https://logo.clearbit.com/aimarketsense.com" },
  { id: 31, name: "AI EnergyGrid", description: "AI for smart grid and energy distribution.", gartnerScore: 4.6, website: "https://aienergygrid.com", logo: "https://logo.clearbit.com/aienergygrid.com" },
  { id: 32, name: "AI SecureHome", description: "Home security and automation with AI.", gartnerScore: 4.2, website: "https://aisecurehome.com", logo: "https://logo.clearbit.com/aisecurehome.com" },
  { id: 33, name: "AI ShopAssist", description: "AI-powered shopping assistants for e-commerce.", gartnerScore: 4.3, website: "https://aishopassist.com", logo: "https://logo.clearbit.com/aishopassist.com" }
];
